name: hello world

on: 
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *" # runs every 5 minutes
  # push:
  #   branches:
  #     - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Show message hello world
        run: echo "Hello world, Simo"
        
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List repo files
        run: |
          echo "The repo ${{ github.repository }} contains the following files:"
          tree
