name: hello world

on: 
  schedule:
    - cron: "*/5 * * * *" # runs every 5 minutes
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Show message hello world
        run: echo "Hello world, Simo"
