name: Passing values with output

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Type a variable
        id: generate-value
        run: echo "MY_VALUE=simo" >> "$GITHUB_OUTPUT"

      - name: Get variable
        run: echo "${{ steps.generate-value.outputs.MY_VALUE }}"

      - name: Masking a value
        id: mask
        run: |
          secret_value=sami
          echo "::add-mask::$secret-value"
          echo "SECRET_VALUE=$secret-value" >> "$GITHUB_OUTPUT"

      - name: Using secret value
        run: | 
          echo "The secret value is: ${{ steps.mask.outputs.SECRET_VALUE }}"
