name: Variables & Secrets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Displaying secrets & variables
        run: |
          echo "The variable is ${{ vars.MY_VARIABLE }}"
          echo "The secret is ${{ secrets.CONNECTION_STRING }}"

      # CENTRALIZED_VARIABLE
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run JS code
        run: node code/main.js
        env: 
          CENTRALIZED_VARIABLE: ${{ vars.MY_VARIABLE }}
